CREATE TABLE AUTHOR (
    ID NUMERIC NOT NULL PRIMARY KEY ,
    NAME VARCHAR(20) NOT NULL
);

CREATE TABLE REFERENCE(
    FULL_ADDRESS VARCHAR(100) NOT NULL ,
    SHORT_ADDRESS VARCHAR(20) NOT NULL PRIMARY KEY ,
    DATE_CREATE DATE NOT NULL ,
    AUTHOR_ID NUMERIC NOT NULL,
    CONSTRAINT REFERENCE_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID)
);
CREATE TABLE Statistics(
Id_Author Number(10),
Ref_Short_Adr VARCHAR(20),
Numb_of_Trans NUMERIC(20),
Last_Trans DATE,
CONSTRAINT PK_Author_Ref PRIMARY KEY (Id_Author, Ref_Short_Adr),
CONSTRAINT FK_Statistic_Author FOREIGN KEY (Id_Author) REFERENCES AUTHOR(ID),
CONSTRAINT FK_Statistic_Ref FOREIGN KEY (Ref_Short_Adr) REFERENCES REFERENCE(SHORT_ADDRESS)
);